### ISSUE TITLE
zip function ?

### ISSUE THREAD

**Issue by tsani** [labs42io/itiriri#5]
Suppose `l1: Iterable<S>` and `l2: Iterable<T>`, then it would be nice to be able to do something like `itiriri(l1).zip(l2).map( ([x, y]) => f(x, y) )`, for example.
I believe with the latest TypeScript features, `zip`'s generics can be variadic so an arbitrary number of other iterables can be zipped in.

**Comment by dimadeveatii** [comment]
Indeed a `zip` function would be nice. For now you could use `groupJoin` instead:
```typescript
l1.groupJoin(l2, (_, i) => i, (_, i) => i, (x, [y]) => f(x, y));
``` 
In the above example it joins items from `l1` with items from `l2` (an array, but in our case we know it's only one element) that matches the same index.  
See [`groupJoin`](https://github.com/labs42io/itiriri#groupjoin) for more details. It is actually a more generalized version of `zip`.
